/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;

import database.DbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilshara Mithum
 */
public class fpass extends javax.swing.JFrame {
 Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form login
     */
    public fpass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorArc2D1 = new org.jdesktop.swing.animation.timing.evaluators.EvaluatorArc2D();
        txt_pass2 = new javax.swing.JPasswordField();
        txt_emailcode = new javax.swing.JTextField();
        txt_pass1 = new javax.swing.JPasswordField();
        txt_username = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ecodev = new javax.swing.JLabel();
        passmatchcheck = new javax.swing.JLabel();
        emailvalid1 = new javax.swing.JLabel();
        statusCode = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_Reset = new javax.swing.JButton();
        backtologin = new javax.swing.JButton();
        closereset = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_sentCode = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginPage");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pass2.setBackground(new java.awt.Color(51, 0, 0));
        txt_pass2.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_pass2.setBorder(null);
        getContentPane().add(txt_pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 260, 30));

        txt_emailcode.setBackground(new java.awt.Color(51, 0, 0));
        txt_emailcode.setForeground(new java.awt.Color(255, 255, 255));
        txt_emailcode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_emailcode.setToolTipText("");
        txt_emailcode.setBorder(null);
        txt_emailcode.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_emailcode.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_emailcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailcodeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_emailcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 260, 30));

        txt_pass1.setBackground(new java.awt.Color(51, 0, 0));
        txt_pass1.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_pass1.setBorder(null);
        getContentPane().add(txt_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 260, 30));

        txt_username.setBackground(new java.awt.Color(51, 0, 0));
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_username.setToolTipText("");
        txt_username.setBorder(null);
        txt_username.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 260, 30));

        txt_email.setBackground(new java.awt.Color(51, 0, 0));
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_email.setToolTipText("");
        txt_email.setBorder(null);
        txt_email.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 260, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_lock_32px.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 30, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_lock_32px.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 50, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_mail_32px.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 40, 50));

        Ecodev.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        Ecodev.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(Ecodev, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 130, 20));

        passmatchcheck.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        passmatchcheck.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(passmatchcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 170, 20));

        emailvalid1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        emailvalid1.setForeground(new java.awt.Color(255, 153, 0));
        getContentPane().add(emailvalid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 170, 20));

        statusCode.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        statusCode.setForeground(new java.awt.Color(255, 255, 255));
        statusCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(statusCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 230, 100, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login/Pallebadda  Public Library.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter New Password");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_user_32px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login/Hue_Saturation 4.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Reset Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 550, 50));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Re-Enter New Password");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 190, -1));

        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/button_reset (1).png"))); // NOI18N
        btn_Reset.setToolTipText("reset");
        btn_Reset.setBorder(null);
        btn_Reset.setBorderPainted(false);
        btn_Reset.setContentAreaFilled(false);
        btn_Reset.setRequestFocusEnabled(false);
        btn_Reset.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/button_reset.png"))); // NOI18N
        btn_Reset.setVerifyInputWhenFocusTarget(false);
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 130, 50));

        backtologin.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        backtologin.setForeground(new java.awt.Color(255, 255, 255));
        backtologin.setText("< Back to Login");
        backtologin.setToolTipText("Close");
        backtologin.setBorder(null);
        backtologin.setBorderPainted(false);
        backtologin.setContentAreaFilled(false);
        backtologin.setRequestFocusEnabled(false);
        backtologin.setVerifyInputWhenFocusTarget(false);
        backtologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologinActionPerformed(evt);
            }
        });
        getContentPane().add(backtologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 550, 40));

        closereset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/cancel (2).png"))); // NOI18N
        closereset.setToolTipText("Close");
        closereset.setBorder(null);
        closereset.setBorderPainted(false);
        closereset.setContentAreaFilled(false);
        closereset.setRequestFocusEnabled(false);
        closereset.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/cancel (3).png"))); // NOI18N
        closereset.setVerifyInputWhenFocusTarget(false);
        closereset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeresetActionPerformed(evt);
            }
        });
        getContentPane().add(closereset, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 40, 40));

        jLabel15.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email Confirm Code");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_email_open_32px.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 50, 50));

        btn_sentCode.setBackground(new java.awt.Color(255, 255, 255));
        btn_sentCode.setForeground(new java.awt.Color(204, 51, 0));
        btn_sentCode.setText("Sent Code");
        btn_sentCode.setToolTipText("");
        btn_sentCode.setFont(new java.awt.Font("Poppins", 1, 10)); // NOI18N
        btn_sentCode.setRippleColor(new java.awt.Color(51, 0, 0));
        btn_sentCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sentCodeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sentCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 90, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login/bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 560));

        setSize(new java.awt.Dimension(1020, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailcodeActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
     
        try {
            reset();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Check Data");
        }
     
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void closeresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeresetActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeresetActionPerformed

    private void backtologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologinActionPerformed
        login log1 = new login();
        log1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backtologinActionPerformed

    private void btn_sentCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sentCodeActionPerformed
      
        
        
        Ecode();
        sentCode();        
    }//GEN-LAST:event_btn_sentCodeActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fpass().setVisible(true);
            }
        });

    }

    
    //Genarate Code for Reset
    int ResetCode = 45724;

    private void Ecode() {

        int max = 5000;
        int min = 1000;
        int n = (int) (Math.random() * (max - min)) + min;

        ResetCode = n;

    }
    
   

    
    
    
    //sent mail
    public String sendMail(String AEmail, String APass, String Email, String Subject, String Body) {
        String Mag = "false";
        final String username = AEmail;
        final String password = APass;

        Properties properties = System.getProperties();
        System.out.println("PROPERTIES " + properties);

        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.starttls.required", "true");
        properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
        properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        properties.put("mail.smtp.ssl.enable", "true");

        properties.setProperty("mail.smtp.ssl.trust", "smtp.gmail.com");

        properties.put("mail.smtp.debug", "true");
        final javax.mail.Session mailSession = javax.mail.Session.getInstance(properties);

        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication("yourgmail@gmail.com", "password");
            }

        });

        try {
            Message message = new MimeMessage(session);

            message.setFrom(new InternetAddress(AEmail)); //user email
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(Email));

            message.setSubject(Subject);
            message.setText(Body);
            Transport.send(message);

            Transport transport = mailSession.getTransport("smtp");
            System.out.println("smtp");

            transport.connect("smtp.gmail.com", "yourgmail@gmail.com", "password");
            System.out.println("smtp connection");
            transport.sendMessage(message, message.getAllRecipients());
            System.out.println("smtp message");

            transport.close();

            Mag = "true";
            return Mag;
        } catch (Exception e) {

            e.printStackTrace();
        }

        return Mag;

    }

    
    
      
    //check emails equals
    public boolean checkEmails(String E1){
      String regex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}";  
          Pattern pattern = Pattern.compile(regex);  
           Matcher matcher = pattern.matcher(E1);  
        
           
           boolean isvaild=false;
           
   if(matcher.matches()==true){
           isvaild=true;
       
   }else{
       emailvalid1.setText("Not Valid Email");
   }
         return isvaild;
        
   
    }
    
    
    
    
    
    
    
    
    
    
    
    
    //Check ResetCode Equality
    public boolean checkECode(int a){
       
        if((a == ResetCode)==true){
           return true; 
        }else{
            Ecodev.setText("Not match");
        return false; 
        }
                
                
        
        
         
    }
    
    
     //check Password equals
    public boolean checkPass(String P1,String P2){
        
          boolean iseq= P1.equals(P2);
         if (iseq==true){
            iseq=true;
         }else{
             
             passmatchcheck.setText("Not match");
             iseq=false;
         }
         
        return iseq;
         
    }
    
    
    
    //Reset 
    
    public void reset(){
        
        String username=txt_username.getText();
        String email=txt_email.getText();
        int code=Integer.parseInt( txt_emailcode.getText()); 
        String P1=txt_pass1.getText();
        String P2=txt_pass2.getText();
       
        
        boolean cc =  checkECode(code);
       boolean ce = checkEmails(email);
        boolean cp =  checkPass(P1,P2);
     
      
        
        if(cc==true && ce==true &&cp==true ){
            boolean isDone=false;
         
            try {
                conn=DbConnect.getConnection();
           String sql="update admin set password=? where username=? && email=?";
           pst=conn.prepareStatement(sql);
           
           pst.setString(1,P1);
           pst.setString(2,username);
           pst.setString(3,email);
             
         int rowCount =pst.executeUpdate();
           if(rowCount>0){
               isDone=true;
           }else{
               isDone=false;
           }
           
      
          } catch (Exception e) {
              
             JOptionPane.showMessageDialog(this, "Not Match data with Database");
          }
            
            
      
         if(isDone==true){
             JOptionPane.showMessageDialog(this, "Reset is Done");
         } else{
               JOptionPane.showMessageDialog(this, "Reset is faild (Entered Data not match with preveious data)");
         }
                 
            
            
            
            
            
            
            
          
        }
        
    }
    
    
    
    
    
    
    

    public void sentCode() {

        String AEmail = "yourgmail@gmail.com";

        String APass = "password";
        String Email = txt_email.getText();
        String Subject = "Password ResetCode";
        String Body = "Your Reset Code is " + ResetCode;

        String Test = sendMail(AEmail, APass, Email, Subject, Body);

        if (Test == "true") {
           statusCode.setText("Done");

        } else {
            JOptionPane.showMessageDialog(this, "Email Sent Fail");
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ecodev;
    private javax.swing.JButton backtologin;
    private javax.swing.JButton btn_Reset;
    private rojerusan.RSMaterialButtonRectangle btn_sentCode;
    private javax.swing.JButton closereset;
    private javax.swing.JLabel emailvalid1;
    private org.jdesktop.swing.animation.timing.evaluators.EvaluatorArc2D evaluatorArc2D1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel passmatchcheck;
    private javax.swing.JLabel statusCode;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailcode;
    private javax.swing.JPasswordField txt_pass1;
    private javax.swing.JPasswordField txt_pass2;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
