/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;

import javax.swing.JOptionPane;

/**
 *
 * @author Dilshara Mithum
 */
public class loading extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingbar = new javax.swing.JProgressBar();
        loadingvalue = new javax.swing.JLabel();
        loadingtext = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginPage");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingbar.setBackground(new java.awt.Color(51, 0, 0));
        loadingbar.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1020, 20));

        loadingvalue.setBackground(new java.awt.Color(255, 255, 255));
        loadingvalue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loadingvalue.setForeground(new java.awt.Color(255, 255, 255));
        loadingvalue.setText("0%");
        getContentPane().add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, -1, -1));

        loadingtext.setBackground(new java.awt.Color(255, 255, 255));
        loadingtext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loadingtext.setForeground(new java.awt.Color(255, 255, 255));
        loadingtext.setText("Loading...");
        getContentPane().add(loadingtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loading/loading.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 560));

        setSize(new java.awt.Dimension(1020, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loading().setVisible(true);
            }
        });
        */
     //   new loading().setVisible(true);
        loading sp=new loading();
        login lp=new login();
       sp.setVisible(true);
  try{

for(int i=0;i<=100;i++){
   
Thread.sleep(100);
sp.loadingvalue.setText(i+"%");

if(i==10){
sp.loadingtext.setText("Turning OS Modules...");
}

if(i==20){
sp.loadingtext.setText("Loading Modules...");
}

if(i==50){
sp.loadingtext.setText("Connecting Database...");
}

if(i==70){
sp.loadingtext.setText("Connection Successful...");
}
if(i==80){
sp.loadingtext.setText("Lunching Application...");
}

sp.loadingbar.setValue(i);
}
sp.setVisible(false);
lp.setVisible(true);

  }catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}

  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadingtext;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables
}
