/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;

import database.DbConnect;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilshara Mithum
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    public login() {
        initComponents();
        
        conn=DbConnect.getConnection();
        
    }

    //validation
    
    public boolean validateLogin(){
        
        String name=unamebox.getText();
         String pwd=String.valueOf(upassbox.getText());
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "Plz Enter UserName");
            return false;
        }
        if (pwd.equals("")){
            JOptionPane.showMessageDialog(this, "Plz Enter Password");
            return false;
        }
      return true;
    }
    
    public void login(){
       String name=unamebox.getText();
         String pwd=upassbox.getText();
         
         try {
           //  Class.forName("org.sqlite.JDBC");
           //   conn=DriverManager.getConnection("jdbc:sqlite:lbs.db");
            
            PreparedStatement pst=conn.prepareStatement("select * from admin where username=? and password=?"); 
            pst.setString(1, name);
            pst.setString(2, pwd);
            
                 rs=pst.executeQuery();
                 if(rs.next()){
                     this.dispose();
                    mainfm mf=new mainfm();
                    mf.setVisible(true);
                    conn.close();
                    
                 }else{
                     JOptionPane.showMessageDialog(this,"Incorrect Username or Password");
                 }
                 
         
         } catch (Exception e) {
            
              JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        upassbox = new javax.swing.JPasswordField();
        unamebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        fbu = new javax.swing.JButton();
        close1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginPage");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 260, 1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 260, 1));

        upassbox.setBackground(new java.awt.Color(51, 0, 0));
        upassbox.setForeground(new java.awt.Color(255, 255, 255));
        upassbox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        upassbox.setBorder(null);
        upassbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upassboxActionPerformed(evt);
            }
        });
        getContentPane().add(upassbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 260, 30));

        unamebox.setBackground(new java.awt.Color(51, 0, 0));
        unamebox.setForeground(new java.awt.Color(255, 255, 255));
        unamebox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        unamebox.setToolTipText("");
        unamebox.setBorder(null);
        unamebox.setCaretColor(new java.awt.Color(255, 255, 255));
        unamebox.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        unamebox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                unameboxFocusLost(evt);
            }
        });
        unamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameboxActionPerformed(evt);
            }
        });
        getContentPane().add(unamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 260, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_password_32px_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 50, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login/Pallebadda  Public Library.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_Account_50px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login/Hue_Saturation 4.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASSWORD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("W E L C O M E");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 550, 110));

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USER NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/button_login (1).png"))); // NOI18N
        login.setToolTipText("login");
        login.setBorder(null);
        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        login.setRequestFocusEnabled(false);
        login.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/button_login (2).png"))); // NOI18N
        login.setVerifyInputWhenFocusTarget(false);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 550, 60));

        fbu.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        fbu.setForeground(new java.awt.Color(255, 255, 255));
        fbu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login/icons8_forgot_password_32px.png"))); // NOI18N
        fbu.setText("FORGOT PASSWORD ?");
        fbu.setToolTipText("Close");
        fbu.setBorder(null);
        fbu.setBorderPainted(false);
        fbu.setContentAreaFilled(false);
        fbu.setRequestFocusEnabled(false);
        fbu.setVerifyInputWhenFocusTarget(false);
        fbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbuActionPerformed(evt);
            }
        });
        getContentPane().add(fbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 550, 40));

        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/cancel (2).png"))); // NOI18N
        close1.setToolTipText("Close");
        close1.setBorder(null);
        close1.setBorderPainted(false);
        close1.setContentAreaFilled(false);
        close1.setRequestFocusEnabled(false);
        close1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/cancel (3).png"))); // NOI18N
        close1.setVerifyInputWhenFocusTarget(false);
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        getContentPane().add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 40, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login/bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 560));

        setSize(new java.awt.Dimension(1020, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameboxActionPerformed

    private void fbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbuActionPerformed
        fpass fp1=new fpass();
        fp1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fbuActionPerformed

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
              System.exit(0);    
             // TODO add your handling code here:
    }//GEN-LAST:event_close1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       if(validateLogin()){
           login();
           ;
       }

 // TODO add your handling code here:
        
       
    }//GEN-LAST:event_loginActionPerformed

    private void unameboxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameboxFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_unameboxFocusLost

    private void upassboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upassboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upassboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close1;
    private javax.swing.JButton fbu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JTextField unamebox;
    private javax.swing.JPasswordField upassbox;
    // End of variables declaration//GEN-END:variables
}
