/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;


import database.DbConnect;
import java.awt.Color;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javaswingdev.message.MessageDialog;

import javax.swing.*;
public class mainfm extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    // Add Color Variablews for Side Menu
 Color mouseEnterColor=new Color(153,51,0);
 Color mouseExitColor=new Color(51,0,0);
 

 Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public mainfm() {
        initComponents();
    
     //call date and time
        dt();
        times(); 
        //add icon for software
     //  Image img=new ImageIcon(this.getClass().getResource("/Images/login/Iconlogo.png")).getImage();
    //  this.setIconImage(img);
       
       
       
    Dashbord dh2=new Dashbord();
    menupanel.removeAll();
  menupanel.add(dh2).setVisible(true);
        
      
        
    }
    
    //Date 
    
    public void dt(){
        Date d=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String dd=sdf.format(d);
        lbl_date.setText(dd);
    }
    
      
// time
 Timer t ;
 SimpleDateFormat st ;
    
public void times(){

   
    
  t = new Timer(0, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        Date dt  =new Date();
        st = new SimpleDateFormat("hh:mm:ss a");
        
        String tt = st.format(dt);
        lbl_time.setText(tt);
        
        }
    });
  
    t.start();
    
    

}
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Logout1 = new javax.swing.JButton();
        close2 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Logout2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_time = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JButton();
        manageBooks = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ManageMembers = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        DashBord = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IssueBook = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ReturnBooks = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ViewRecords = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ViewIssuedBooks = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DefaulterList = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Reservations = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginPage");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanel1.add(menupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 990, 670));

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Library Management System");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 50));

        Logout1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        Logout1.setForeground(new java.awt.Color(255, 255, 255));
        Logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_Logout_32px_3.png"))); // NOI18N
        Logout1.setText("Logout");
        Logout1.setToolTipText("Logout");
        Logout1.setBorder(null);
        Logout1.setBorderPainted(false);
        Logout1.setContentAreaFilled(false);
        Logout1.setRequestFocusEnabled(false);
        Logout1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_Logout_32px_2.png"))); // NOI18N
        Logout1.setVerifyInputWhenFocusTarget(false);
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });
        jPanel4.add(Logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 100, 50));

        close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/cancel (2).png"))); // NOI18N
        close2.setToolTipText("Close");
        close2.setBorder(null);
        close2.setBorderPainted(false);
        close2.setContentAreaFilled(false);
        close2.setRequestFocusEnabled(false);
        close2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/cancel (3).png"))); // NOI18N
        close2.setVerifyInputWhenFocusTarget(false);
        close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close2ActionPerformed(evt);
            }
        });
        jPanel4.add(close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 50));

        Logout.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_settings_32px_1.png"))); // NOI18N
        Logout.setText("Account");
        Logout.setToolTipText("Logout");
        Logout.setBorder(null);
        Logout.setBorderPainted(false);
        Logout.setContentAreaFilled(false);
        Logout.setRequestFocusEnabled(false);
        Logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_settings_32px_3.png"))); // NOI18N
        Logout.setVerifyInputWhenFocusTarget(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel4.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 110, 50));

        Logout2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        Logout2.setForeground(new java.awt.Color(255, 255, 255));
        Logout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_library_32px_2.png"))); // NOI18N
        Logout2.setText("About");
        Logout2.setToolTipText("Logout");
        Logout2.setBorder(null);
        Logout2.setBorderPainted(false);
        Logout2.setContentAreaFilled(false);
        Logout2.setRequestFocusEnabled(false);
        Logout2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/icons/icons/icons8_library_32px_1.png"))); // NOI18N
        Logout2.setVerifyInputWhenFocusTarget(false);
        Logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout2ActionPerformed(evt);
            }
        });
        jPanel4.add(Logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 100, 50));

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));

        lbl_time.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setText("07:55:37 PM");

        lbl_date.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setText("2022-19-07");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/icons8_timeline_week_20px.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/icons8_time_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 280, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 990, 50));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(529, 300));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/logo.png"))); // NOI18N
        logo.setToolTipText("logo");
        logo.setBorder(null);
        logo.setBorderPainted(false);
        logo.setContentAreaFilled(false);
        logo.setRequestFocusEnabled(false);
        logo.setVerifyInputWhenFocusTarget(false);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });

        manageBooks.setBackground(new java.awt.Color(51, 0, 0));
        manageBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageBooksMouseExited(evt);
            }
        });
        manageBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_book_shelf_32px.png"))); // NOI18N
        jLabel9.setText("  Manage Books");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        manageBooks.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        ManageMembers.setBackground(new java.awt.Color(51, 0, 0));
        ManageMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageMembersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageMembersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageMembersMouseExited(evt);
            }
        });
        ManageMembers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        jLabel10.setText("  Manage Members");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ManageMembers.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        DashBord.setBackground(new java.awt.Color(51, 0, 0));
        DashBord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashBordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashBordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashBordMouseExited(evt);
            }
        });
        DashBord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_library_building_32px_1.png"))); // NOI18N
        jLabel2.setText("   DASHBORD");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DashBord.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 160, 40));

        IssueBook.setBackground(new java.awt.Color(51, 0, 0));
        IssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IssueBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IssueBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IssueBookMouseExited(evt);
            }
        });
        IssueBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        jLabel4.setText("    Issue Book");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        IssueBook.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        ReturnBooks.setBackground(new java.awt.Color(51, 0, 0));
        ReturnBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReturnBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReturnBooksMouseExited(evt);
            }
        });
        ReturnBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        jLabel5.setText("    Return Book");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ReturnBooks.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        ViewRecords.setBackground(new java.awt.Color(51, 0, 0));
        ViewRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewRecordsMouseExited(evt);
            }
        });
        ViewRecords.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        jLabel6.setText("    View Records");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ViewRecords.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        ViewIssuedBooks.setBackground(new java.awt.Color(51, 0, 0));
        ViewIssuedBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewIssuedBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewIssuedBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewIssuedBooksMouseExited(evt);
            }
        });
        ViewIssuedBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_Books_26px.png"))); // NOI18N
        jLabel7.setText("   View Issued Books");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ViewIssuedBooks.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 190, 30));

        DefaulterList.setBackground(new java.awt.Color(51, 0, 0));
        DefaulterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DefaulterListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DefaulterListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DefaulterListMouseExited(evt);
            }
        });
        DefaulterList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        jLabel8.setText("   Defaulter List");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DefaulterList.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        Reservations.setBackground(new java.awt.Color(51, 0, 0));
        Reservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservationsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReservationsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReservationsMouseExited(evt);
            }
        });
        Reservations.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/adminIcons/adminIcons/icons8_book_32px_1.png"))); // NOI18N
        jLabel19.setText(" Reservations");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Reservations.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 170, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewIssuedBooks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewRecords, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReturnBooks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IssueBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(DashBord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DefaulterList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DashBord, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(IssueBook, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewIssuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DefaulterList, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reservations, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/mback.png"))); // NOI18N
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1280, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1PropertyChange

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed

    private void close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close2ActionPerformed
//       

MessageDialog obj = new MessageDialog(this);
        obj.showMessage("DO you want to Close the Application", "");
        if (obj.getMessageType() == MessageDialog.MessageType.OK) {
            System.out.println("User click ok");
            System.exit(0);
        } else {
            System.out.println("User click cancel");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_close2ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
       setting st=new setting();
       st.setVisible(true);
       this.dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
 try{
    
    login lg2=new login();
        lg2.setVisible(true);
       this.dispose();  
        
        // TODO add your handling code here:
 }catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_Logout1ActionPerformed

    private void IssueBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBookMouseEntered
        // TODO add your handling code here:
         IssueBook.setBackground(mouseEnterColor);
        
    }//GEN-LAST:event_IssueBookMouseEntered

    private void IssueBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBookMouseExited
        // TODO add your handling code here:
      IssueBook.setBackground(mouseExitColor);   
    }//GEN-LAST:event_IssueBookMouseExited

    private void ViewIssuedBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewIssuedBooksMouseClicked
       
 ViewIssuedBooks vi1=new ViewIssuedBooks();
        menupanel.removeAll();
        menupanel.add(vi1).setVisible(true);
        
// TODO add your handling code here:
        
         
         
    }//GEN-LAST:event_ViewIssuedBooksMouseClicked

    private void DefaulterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefaulterListMouseClicked
        // TODO add your handling code here:
 DefaulterBooks DF1=new DefaulterBooks();
        menupanel.removeAll();
        menupanel.add(DF1).setVisible(true);
        
        
   
    }//GEN-LAST:event_DefaulterListMouseClicked

    private void ManageMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageMembersMouseClicked
        // TODO add your handling code here:
      ManageMembers MM1=new ManageMembers();
        menupanel.removeAll();
        menupanel.add(MM1).setVisible(true);  
                
                
    }//GEN-LAST:event_ManageMembersMouseClicked

    private void ReservationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationsMouseClicked


  
 Reservations rs1=new Reservations();
        menupanel.removeAll();
        menupanel.add(rs1).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservationsMouseClicked

    private void IssueBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IssueBookMouseClicked
        // TODO add your handling code here:
        
        IssueBooks ib1=new IssueBooks();
        menupanel.removeAll();
        menupanel.add(ib1).setVisible(true);
    }//GEN-LAST:event_IssueBookMouseClicked

    private void DashBordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBordMouseEntered
        // TODO add your handling code here:
        DashBord.setBackground(mouseEnterColor);
    }//GEN-LAST:event_DashBordMouseEntered

    private void DashBordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBordMouseExited
 DashBord.setBackground(mouseExitColor);        // TODO add your handling code here:
    }//GEN-LAST:event_DashBordMouseExited

    private void ReservationsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationsMouseEntered
       Reservations.setBackground(mouseEnterColor); // TODO add your handling code here:
    }//GEN-LAST:event_ReservationsMouseEntered

    private void ReservationsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationsMouseExited
       Reservations.setBackground(mouseExitColor);  // TODO add your handling code here:
    }//GEN-LAST:event_ReservationsMouseExited

    private void DashBordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBordMouseClicked
        // TODO add your handling code here:
        
        Dashbord dh1=new Dashbord();
        menupanel.removeAll();
        menupanel.add(dh1).setVisible(true);
        
    }//GEN-LAST:event_DashBordMouseClicked

    private void ReturnBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBooksMouseClicked
        // TODO add your handling code here:
        
        
       ReturnBooks rb1=new ReturnBooks();
        menupanel.removeAll();
        menupanel.add(rb1).setVisible(true);
    }//GEN-LAST:event_ReturnBooksMouseClicked

    private void ViewRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewRecordsMouseClicked
       ViewRecords vr1=new ViewRecords();
        menupanel.removeAll();
        menupanel.add(vr1).setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_ViewRecordsMouseClicked

    private void manageBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBooksMouseClicked
     

ManageBooks mb1=new ManageBooks();
     menupanel.removeAll();
   menupanel.add(mb1).setVisible(true);
  
 
  

// TODO add your handling code here:
    }//GEN-LAST:event_manageBooksMouseClicked

    private void ReturnBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBooksMouseEntered
        // TODO add your handling code here:
        ReturnBooks.setBackground(mouseEnterColor);
    }//GEN-LAST:event_ReturnBooksMouseEntered

    private void ReturnBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnBooksMouseExited
        // TODO add your handling code here:
        ReturnBooks.setBackground(mouseExitColor);

    }//GEN-LAST:event_ReturnBooksMouseExited

    private void ViewRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewRecordsMouseEntered
        // TODO add your handling code here:
        ViewRecords.setBackground(mouseEnterColor);
    }//GEN-LAST:event_ViewRecordsMouseEntered

    private void ViewRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewRecordsMouseExited
        ViewRecords.setBackground(mouseExitColor);        // TODO add your handling code here:
    }//GEN-LAST:event_ViewRecordsMouseExited

    private void ViewIssuedBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewIssuedBooksMouseEntered
        ViewIssuedBooks.setBackground(mouseEnterColor);// TODO add your handling code here:
    }//GEN-LAST:event_ViewIssuedBooksMouseEntered

    private void ViewIssuedBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewIssuedBooksMouseExited
      ViewIssuedBooks.setBackground(mouseExitColor);    // TODO add your handling code here:
    }//GEN-LAST:event_ViewIssuedBooksMouseExited

    private void DefaulterListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefaulterListMouseEntered
     DefaulterList.setBackground(mouseEnterColor);  // TODO add your handling code here:
    }//GEN-LAST:event_DefaulterListMouseEntered

    private void DefaulterListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DefaulterListMouseExited
        DefaulterList.setBackground(mouseExitColor);// TODO add your handling code here:
    }//GEN-LAST:event_DefaulterListMouseExited

    private void manageBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBooksMouseEntered
       manageBooks.setBackground(mouseEnterColor); // TODO add your handling code here:
    }//GEN-LAST:event_manageBooksMouseEntered

    private void manageBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBooksMouseExited
       manageBooks.setBackground(mouseExitColor);
 // TODO add your handling code here:
    }//GEN-LAST:event_manageBooksMouseExited

    private void ManageMembersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageMembersMouseEntered
      ManageMembers.setBackground(mouseEnterColor);  // TODO add your handling code here:
    }//GEN-LAST:event_ManageMembersMouseEntered

    private void ManageMembersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageMembersMouseExited
      ManageMembers.setBackground(mouseExitColor);  // TODO add your handling code here:
    }//GEN-LAST:event_ManageMembersMouseExited

    private void Logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout2ActionPerformed
aboutlib lb=new aboutlib();
       lb.setVisible(true);
       this.dispose();        
// TODO add your handling code here:
    }//GEN-LAST:event_Logout2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainfm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainfm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainfm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainfm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainfm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DashBord;
    private javax.swing.JPanel DefaulterList;
    private javax.swing.JPanel IssueBook;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Logout1;
    private javax.swing.JButton Logout2;
    private javax.swing.JPanel ManageMembers;
    private javax.swing.JPanel Reservations;
    private javax.swing.JPanel ReturnBooks;
    private javax.swing.JPanel ViewIssuedBooks;
    private javax.swing.JPanel ViewRecords;
    private javax.swing.JButton close2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JButton logo;
    private javax.swing.JPanel manageBooks;
    private javax.swing.JPanel menupanel;
    // End of variables declaration//GEN-END:variables
}
