/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package inf;

import database.DbConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dilshara Mithum
 */
public class ViewIssuedBooks extends javax.swing.JInternalFrame {
Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model;
    /**
     * Creates new form IssueBooks
     */
    public ViewIssuedBooks() {
        initComponents();
        setIBDetailsToTable();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    
    
    //Load Data to table
    public void setIBDetailsToTable() {

        try {
            conn = DbConnect.getConnection();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from issueBooks where Status='"+"Pending"+"'");

            while (rs.next()) {
                String id = rs.getString("id");
                String bookName = rs.getString("BookName");
                String memName = rs.getString("MemberName");
                Date iDate = rs.getDate("IssueDate");
                Date rDate = rs.getDate("ReturnDate");
                String status = rs.getString("Status");

                Object[] obj = {id, bookName, memName, iDate, rDate, status};
                model = (DefaultTableModel) tbl_iDetails.getModel();
                model.addRow(obj);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Add Correct Details");
        }

    }

    //clear table
    public void clerMemTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_iDetails.getModel();
        model.setRowCount(0);
    }

    //to get record with dates
    public void search() {

        Date id1 = idate.getDatoFecha();
        Date rd1 = idate2.getDatoFecha();

        Long l1 = id1.getTime();
        Long l2 = rd1.getTime();

        java.sql.Date id2 = new java.sql.Date(l1);
        java.sql.Date rd2 = new java.sql.Date(l2);

        try {
            conn = DbConnect.getConnection();
            String sql = "select * from issueBooks where IssueDate BETWEEN ? and ? ";
            pst = conn.prepareStatement(sql);
            pst.setDate(1, id2);
            pst.setDate(2, rd2);
            
            rs = pst.executeQuery();
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "No Record Found");
            } else {
                while (rs.next()) {
                    String id = rs.getString("id");
                    String bookName = rs.getString("BookName");
                    String memName = rs.getString("MemberName");
                    Date iDate = rs.getDate("IssueDate");
                    Date rDate = rs.getDate("ReturnDate");
                    String status = rs.getString("Status");

                    Object[] obj = {id, bookName, memName, iDate, rDate, status};
                    model = (DefaultTableModel) tbl_iDetails.getModel();
                    model.addRow(obj);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_iDetails = new rojeru_san.complementos.RSTableMetro();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        idate = new rojeru_san.componentes.RSDateChooser();
        jLabel15 = new javax.swing.JLabel();
        idate2 = new rojeru_san.componentes.RSDateChooser();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel14 = new javax.swing.JLabel();
        clear = new rojerusan.RSMaterialButtonRectangle();
        btn_export = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 0, 0));
        setMaximumSize(new java.awt.Dimension(990, 670));
        setMinimumSize(new java.awt.Dimension(990, 670));
        setPreferredSize(new java.awt.Dimension(990, 670));

        jPanel1.setMaximumSize(new java.awt.Dimension(990, 670));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 670));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 670));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_iDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "Member Name", "Issue Date", "Return Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_iDetails.setColorBackgoundHead(new java.awt.Color(51, 0, 0));
        tbl_iDetails.setColorFilasBackgound2(new java.awt.Color(247, 230, 220));
        tbl_iDetails.setColorFilasForeground1(new java.awt.Color(153, 51, 0));
        tbl_iDetails.setColorFilasForeground2(new java.awt.Color(153, 51, 0));
        tbl_iDetails.setColorSelBackgound(new java.awt.Color(153, 51, 0));
        tbl_iDetails.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        tbl_iDetails.setFuenteFilas(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tbl_iDetails.setFuenteFilasSelect(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        tbl_iDetails.setFuenteHead(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        tbl_iDetails.setGrosorBordeFilas(0);
        tbl_iDetails.setGrosorBordeHead(0);
        jScrollPane2.setViewportView(tbl_iDetails);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 890, 340));

        jPanel16.setBackground(new java.awt.Color(153, 51, 0));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(80, 0, 0, 0, new java.awt.Color(51, 0, 0)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/pic40/icons8_give_40px_1.png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel13.setFocusable(false);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 50, 50));

        jLabel19.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Issue Date:");
        jPanel16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        idate.setBackground(new java.awt.Color(51, 0, 0));
        idate.setForeground(new java.awt.Color(51, 0, 0));
        idate.setToolTipText("");
        idate.setColorBackground(new java.awt.Color(204, 51, 0));
        idate.setColorButtonHover(new java.awt.Color(255, 102, 0));
        idate.setColorForeground(new java.awt.Color(51, 0, 0));
        idate.setColorSelForeground(new java.awt.Color(51, 0, 0));
        idate.setColorTextDiaActual(new java.awt.Color(51, 0, 0));
        idate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        idate.setPlaceholder("     Select date");
        jPanel16.add(idate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 260, -1));

        jLabel15.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Issue Date:");
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        idate2.setBackground(new java.awt.Color(51, 0, 0));
        idate2.setForeground(new java.awt.Color(51, 0, 0));
        idate2.setColorBackground(new java.awt.Color(204, 51, 0));
        idate2.setColorButtonHover(new java.awt.Color(255, 102, 0));
        idate2.setColorForeground(new java.awt.Color(51, 0, 0));
        idate2.setColorSelForeground(new java.awt.Color(51, 0, 0));
        idate2.setColorTextDiaActual(new java.awt.Color(51, 0, 0));
        idate2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        idate2.setPlaceholder("     Select date");
        jPanel16.add(idate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 260, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(204, 51, 0));
        rSMaterialButtonRectangle1.setText("Search");
        rSMaterialButtonRectangle1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        rSMaterialButtonRectangle1.setRippleColor(new java.awt.Color(51, 0, 0));
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel16.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 220, 50));

        jLabel14.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" Issued Book Records");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel14.setFocusable(false);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel16.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 370, 50));

        clear.setBackground(new java.awt.Color(204, 51, 0));
        clear.setText("Clear");
        clear.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        clear.setRippleColor(new java.awt.Color(51, 0, 0));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel16.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 220, 50));

        btn_export.setBackground(new java.awt.Color(204, 51, 0));
        btn_export.setText("Export ");
        btn_export.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_export.setRippleColor(new java.awt.Color(51, 0, 0));
        btn_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportActionPerformed(evt);
            }
        });
        jPanel16.add(btn_export, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 110, 50));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 890, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main/mback.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
        
        
    clerMemTable(); 
    search();
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clerMemTable();
        setIBDetailsToTable();
    }//GEN-LAST:event_clearActionPerformed

    private void btn_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportActionPerformed

        // TODO add your handling code here:

      
        MessageFormat header=new MessageFormat("Issued Books Reort");
        MessageFormat footer=new MessageFormat("page{0,number,integer}");
        try {
            tbl_iDetails.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_btn_exportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_export;
    private rojerusan.RSMaterialButtonRectangle clear;
    private rojeru_san.componentes.RSDateChooser idate;
    private rojeru_san.componentes.RSDateChooser idate2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojeru_san.complementos.RSTableMetro tbl_iDetails;
    // End of variables declaration//GEN-END:variables
}
